### ISSUE TITLE
Week 3: Part 2 reading questions refer to 5.7

### ISSUE THREAD

**Issue by astahfrom** [suneman/socialgraphs2016#1]
The notebook says (1)

> Reading: Now we dig into the extended history and and theory behind Scale-Free networks and the Barabasi-Albert Model.
> 
> Chapter 4, Section 4.1 - 4.7.
> Chapter 5, section 5.1 - 5.5.

but then the second reading comprehension question is (2)

> What are the three regimes we find in non-linear preferential attachement? (chapter 5) Briefly describe each one.

Non-linear preferential attachment is not covered until section 5.7 of the book.
Either (1) should be updated to include 5.7 or (2) should mention 5.7 explicitly to minimise confusion.

**Comment by suneman** [comment]
Good catch! Now fixed - keep them coming :)
